### ISSUE TITLE
Enhanced emulator

### ISSUE THREAD

**Issue by vidya88** [SkycoinProject/hardware-wallet#21]
@olemis commented on Mar 12

**Feature description**

Implement a more realistic emulator

**Is your feature request related to a problem? Please describe.**
Current emulator is substantially different from firmware binary.

**Describe the solution you'd like**
Implement an emulator that:

- [ ]  Runs firmware ARM instructions
- [ ]  Virtualizes an USB connection
- [ ]  Identifies itself like Skywallets (e.g. via usb , hid , udev in GNU/Linux)
- [ ]  Simulates MCU features like MPU , PCROP, RDP , status bits , ...

**Describe alternatives you've considered**
No candidates so far ...

**Additional context**
It might not be feasible to implement some of the features requested .

**Comment by Midren** [comment]
Too much time should be wasted to develop it with small benefits.
