### ISSUE TITLE
Cleaning and refactoring code in fsm.c and fsm_impl.c

### ISSUE THREAD

**Issue by vidya88** [SkycoinProject/hardware-wallet#6]
@RomanMilishchuk commented on Jul 1

**Cleaning code in fsm.c and fsm_impl.c**

Refactoring of the files above to enhance readibility and productivity of code.

**Is your feature request related to a problem? Please describe.**
The main problem is that code is hard to read for beginners and some points are hard to understand.

**Describe the solution you'd like**
The problems, that are found are below in comments:

**Comment by vidya88** [comment]
@YuraYelisieiev commented on Jul 1

While reviewing the code of [fsm_impl.c](https://github.com/skycoin/hardware-wallet/blob/12968889ca8d5e96201e2defeb92e2c137911f73/tiny-firmware/firmware/fsm.c), we found that there are a lot of defined functions there. Which increase the size of the binary because of every usage of the macros unfolds in the ASM, so if we are using macros often it enlarges our binary significantly. We must rewrite it into the function calls.

**Comment by vidya88** [comment]
@RomanMilishchuk commented on Jul 1

fsm.c and fsm_impl.c are too oversized and can be divided into smaller files, which will decrease the time of compilation because a compiler will work only with files, that you changed.

In the next version will be integration also of Bitcoin, so natural division on parts, that are not connected to any currency (only to device itself) and functions, that are connected to Skycoin.

**Comment by vidya88** [comment]
@olemis commented on Jul 1

thanks for creating this issue , this is not priority for v1 though

**Comment by vidya88** [comment]
@stdevAlDen commented on Jul 1

> @YuraYelisieiev commented on Jul 1
> 
> While reviewing the code of [fsm_impl.c](https://github.com/skycoin/hardware-wallet/blob/12968889ca8d5e96201e2defeb92e2c137911f73/tiny-firmware/firmware/fsm.c), we found that there are a lot of defined functions there. Which increase the size of the binary because of every usage of the macros unfolds in the ASM, so if we are using macros often it enlarges our binary significantly. We must rewrite it into the function calls.

@YuraYelisieiev it's ok but is important to check the macros to check out how this apply, for example this is a check pin:

> hardware-wallet/tiny-firmware/firmware/fsm_impl.h
> 
> Lines 58 to 61 in 1296888
> 
>  #define CHECK_PIN_RET_ERR_CODE \ 
>      if (!protectPin(true)) {   \ 
>          return ErrPinRequired; \ 
>      } 

initialized

> hardware-wallet/tiny-firmware/firmware/fsm_impl.h
> 
> Lines 28 to 39 in 1296888
> 
>  #define RESP_INIT(TYPE) GET_MSG_POINTER(TYPE, resp); 
>   
>  #define CHECK_INITIALIZED                                          \ 
>      if (!storage_isInitialized()) {                                \ 
>          fsm_sendFailure(FailureType_Failure_NotInitialized, NULL, 0); \ 
>          return;                                                    \ 
>      } 
>   
>  #define CHECK_INITIALIZED_RET_ERR_CODE \ 
>      if (!storage_isInitialized()) {    \ 
>          return ErrInitialized;         \ 
>      } 

init

> hardware-wallet/tiny-firmware/firmware/fsm_impl.h
> 
> Lines 23 to 28 in 1296888
> 
>  #define GET_MSG_POINTER(TYPE, VarName)                                       \ 
>      TYPE* VarName = (TYPE*)(void*)msg_resp;                                  \ 
>      _Static_assert(sizeof(msg_resp) >= sizeof(TYPE), #TYPE " is too large"); \ 
>      memset(VarName, 0, sizeof(TYPE)); 
>   
>  #define RESP_INIT(TYPE) GET_MSG_POINTER(TYPE, resp); 

so, can you find one that as function call is a better alternative?

**Comment by vidya88** [comment]
@SkycoinSynth commented 2 days ago

Removing the macros may increase the binary size.

**Comment by vidya88** [comment]
@RomanMilishchuk commented 2 days ago

@SkycoinSynth when you are using macro, then it on the time of preprocessing replaces the macro with the code (like inline functions), so actually using of macro increase the binary size, if they are used more then one time. Functions decrease the binary size but use more memory in the runtime, because of the stack frames.

**Comment by Midren** [comment]
Fixed in https://github.com/skycoin/hardware-wallet/pull/349
